// API pública del slice "permiso". Nada fuera de esta carpeta debe importar
// directo desde api/ — todo pasa por este barrel.
export {
  permissionApi,
  type PermissionCatalog,
  type MatrixCell,
  type RolesAdminData,
  type MatrixChange,
  type CatalogCreateDto,
  type CatalogUpdateDto,
  type RoleAdmin,
  type RoleCreateDto,
  type RoleUpdateDto,
  type PolicyAdmin,
  type PolicyCondition,
  type PolicyCreateDto,
  type PolicyUpdateDto,
  type PolicyEffect,
  type PolicyActionDef,
  type PolicyFieldDef,
  type PolicyFieldType,
  type PolicyListData,
  type AccessMember,
  type AccessException,
  type AccessPermissionView,
  type UserAccessView,
  type ConditionTrace,
  type RuleTrace,
  type PolicyExplanation,
  type SimulationDto,
  type AccessSimulation,
  type AccessActivityRow,
  ACCESS_ACTIVITY_ACTIONS,
} from "./api/permissionApi";
export {
  APP_SCREENS,
  isScreenVisible,
  isScreenVisibleInGroup,
  referencedPermissions,
  screenHasPermission,
  screenLeaves,
  screenScopeOf,
  screenActions,
  screenRequirementKeys,
  type AppScreen,
  type NavLabelKey,
  type PermissionMap,
  type ScreenLeaf,
  type ScreenRequirement,
} from "./model/screens";
